language: node_js
node_js:
 - "12.2"

branches:
  only:
    - master

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng lint
  - ng build --prod